classDiagram
%% @backgroundColor(#252525)
    EventDispatcher <|-- KeyboardInput
    KeyboardInput o-- MainActor
    KeyboardInput o-- MovementLogger
    KeyboardInput : on_key_press()
    MainActor : move_left()
    MovementLogger : move_left()
    class EventDispatcher{
        +register_event_type()
        +dispatch_event()
        +push_handlers()
    }