classDiagram
%% @backgroundColor(#252525)
    arcade_Window o-- BaseState
    BaseState <|-- MainMenu
    BaseState <|-- Gameplay
    BaseState <|-- Paused
    BaseState <|-- Info
    class BaseState{
        +window
        +game_logic
        +player
        +set_next_state()
    }